#!/usr/bin/env Rscript
install.packages("rgeos")
install.packages("rgdal")
# raster install not working
install.packages('raster',  repos='http://cran.us.r-project.org')
install.packages('ncdf4')
install.packages("xlsx")
install.packages("ggmap")
library(raster)
library(rgdal)
install.packages("Rserve")
library(Rserve)
source('/home/rstudio/downloadAndUnzipShp.R')
source('/home/rstudio/edificationSaoPaulo.R')
source('/home/rstudio/equipamentosSaoPaulo.R')
source('/home/rstudio/shapefilesProcessing.R')
Rserve(args="--no-save  --RS-enable-remote")
